### ISSUE TITLE
BigInt doesn't seem to work. 

### ISSUE THREAD

**Issue by meech-ward** [typed-rocks/ts-worksheet#2]
If I throw a bigint into my file, all ts-worksheet types disappear.
### **Works fine, big int is converted to boolean:**
![Screenshot 2024-03-05 at 1 59 08 PM](https://github.com/typed-rocks/ts-worksheet/assets/2434008/9f3584e7-fe53-43dc-878a-7963551c176a)
### **Seems to break when evaluating BigInt:**
![Screenshot 2024-03-05 at 1 59 20 PM](https://github.com/typed-rocks/ts-worksheet/assets/2434008/0afd535c-8dc9-4fdf-879b-ce6d87209971)

**Comment by chwoerz** [comment]
Thank you 🙏 I will look into it and come back to you as soon as it's fixed

**Comment by chwoerz** [comment]
@meech-ward Version 0.8.2 is now ready which fixes the issue: 
![Bildschirmfoto 2024-03-06 um 08 33 47](https://github.com/typed-rocks/ts-worksheet/assets/4927839/40638413-c141-48a8-9e13-1667d267516b)

**Comment by chwoerz** [comment]
@meech-ward thanks a lot. Also found a but regarding NaN which is also fixed 🙏
