### ISSUE TITLE
Can't install 'chwoerz.ts-worksheet' extension because it is not compatible with the current version of Visual Studio Code (version 1.84.2).

### ISSUE THREAD

**Issue by eric12342022** [typed-rocks/ts-worksheet#3]
It's a message from vscode IDE. Is that any compatiable version of vs code can be used?

**Comment by chwoerz** [comment]
Hey, I will check if I can make the requirement lower 👍. Will message you as soon as it's done. :)

**Comment by chwoerz** [comment]
Version 0.8.8 is released and now supports 1.83  👍
